{"name": "Verificar que un usuario puede iniciar sesión correctamente con credenciales válidas", "status": "broken", "statusDetails": {"message": "TypeError: Locator.click() got an unexpected keyword argument 'timeot'. Did you mean 'timeout'?\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/login_steps.py\", line 15, in step_impl\n    context.login_page.login(Config.VALID_USERNAME, Config.VALID_PASSWORD)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ceciliaperez/Desktop/DGII-Automatizacion/pages/login_page.py\", line 21, in login\n    self.click_element(self.login_button)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ceciliaperez/Desktop/DGII-Automatizacion/pages/base_page.py\", line 13, in click_element\n    self.page.locator(selector).click(timeot=timeot)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given que estoy en la página de inicio de sesión", "status": "passed", "start": 1751746039860, "stop": 1751746041609}, {"name": "When introduzco un nombre de usuario y contraseña válidos", "status": "broken", "statusDetails": {"message": "TypeError: Locator.click() got an unexpected keyword argument 'timeot'. Did you mean 'timeout'?\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/login_steps.py\", line 15, in step_impl\n    context.login_page.login(Config.VALID_USERNAME, Config.VALID_PASSWORD)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ceciliaperez/Desktop/DGII-Automatizacion/pages/login_page.py\", line 21, in login\n    self.click_element(self.login_button)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ceciliaperez/Desktop/DGII-Automatizacion/pages/base_page.py\", line 13, in click_element\n    self.page.locator(selector).click(timeot=timeot)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "start": 1751746041609, "stop": 1751746041666}, {"name": "And hago clic en el botón de Login", "status": "skipped", "start": 1751746041788, "stop": 1751746041788}, {"name": "Then debería ser redirigido al tablero con un mensaje de bienvenida \"You logged into a secure area!\"", "status": "skipped", "start": 1751746041788, "stop": 1751746041788}, {"name": "And cierro sesión", "status": "skipped", "start": 1751746041788, "stop": 1751746041788}], "attachments": [{"name": "Failure Screenshot", "source": "b7e1954f-8d92-441e-b84e-2fc337b86cde-attachment.png", "type": "image/png"}], "start": 1751746039433, "stop": 1751746041788, "uuid": "e05907b9-6c5e-4030-b5f1-6d19e163b1d5", "historyId": "5e2016984f1b8795171c53a319a2679a", "fullName": "Funcionalidad de Inicio de Sesión de Usuario: Verificar que un usuario puede iniciar sesión correctamente con credenciales válidas", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login_valid"}, {"name": "feature", "value": "Funcionalidad de Inicio de Sesión de Usuario"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}